FROM node:20-slim AS frontend-builder
WORKDIR /frontend
COPY rentcar-ec-frontend/package*.json ./
RUN npm install
COPY rentcar-ec-frontend/ .
RUN npm run build

FROM nginx:alpine
COPY --from=frontend-builder /frontend/dist /usr/share/nginx/html
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
